d = dict()
text = "CATTCAGCCATCACTAGAGACGAGGGCGTCACTAGAGACGAGGGCGCATTCAGCCAGACGAGGGCGGACGAGGGCGGACGAGGGCGACGACCACCCATTCAGCCAGACGAGGGCGTCACTAGAACGACCACCACGACCACCACGACCACCCATTCAGCCACATTCAGCCAGACGAGGGCGCATTCAGCCAGTGATCCCGTGATCCCACGACCACCCATTCAGCCATCACTAGATCACTAGAGTGATCCCTCACTAGAGTGATCCCTCACTAGACATTCAGCCAGACGAGGGCGACGACCACCGTGATCCCCATTCAGCCAGACGAGGGCGCATTCAGCCAACGACCACCGACGAGGGCGCATTCAGCCAGACGAGGGCGGTGATCCCGTGATCCCTCACTAGAGTGATCCCTCACTAGAGTGATCCCGACGAGGGCGGACGAGGGCGGACGAGGGCGGACGAGGGCGGACGAGGGCGGTGATCCCGTGATCCCTCACTAGAGTGATCCCGTGATCCCACGACCACCTCACTAGATCACTAGAACGACCACCTCACTAGAGACGAGGGCGACGACCACCTCACTAGAACGACCACCGACGAGGGCGACGACCACCCATTCAGCCAACGACCACCTCACTAGAGTGATCCCGACGAGGGCGACGACCACCCATTCAGCCAACGACCACCGACGAGGGCGCATTCAGCCAGTGATCCCCATTCAGCCACATTCAGCCAGTGATCCCGTGATCCCGACGAGGGCGGACGAGGGCGGACGAGGGCGTCACTAGAACGACCACCACGACCACCTCACTAGATCACTAGAGACGAGGGCGACGACCACCGTGATCCCCATTCAGCCACATTCAGCCACATTCAGCCACATTCAGCCATCACTAGAACGACCACC"
k = 14
for i in range(len(text)-k+1):
  p = text[i:i+k]
  if p in d.keys():
    d[p] += 1
  else:
    d[p] = 1

mx = max(d.values())
ans = []
for k in d:
  if d[k] == mx:
    ans.append(k)
val = sorted(ans)
for i in val:
  print(i, end=" ")
