dna = "AGGCGGTGGGTTGGCTCTGATATGCCCGTGACGGTTCTTACGGCTGGCAGAACACCCAATTAATAAAACTCCATAGTGCTCCATTGTATCGCACCCACTACGTTGGCGTTCCCTAAACCTCATACAAGCCCATTATAGTACAGGTTGCTTGACACTGATGAGGGTGCAGGGTGCACCGCCGGTGAATCTCCCGTCCATGTCTCAGGCCACACCGGGACCAGTGGTCATTGATGCCACTAGGAAAAAAGTGCAAGCTATCTAATCGAGTTTCGTACGCGCTCTAATCTGAAAGTGCTCTTTACACGATTCCTTGCTGTGAATCCTCCAGGCTTATGGGCGATTAACGCAACGCTGTCGTTGGTCCCGCCGAAGTGCTCAGTTTACCCAGCGGTCAGCGTTCGAGGAAAGATCCCCAGCACCCATGCCTCACGCTAATCTTTATACTGGATACTAAATTTGTTCAGATGGCAAACTTCTTCAGACGATGGTTAAATGAAGGCGGGGTGTTCACCCCTTGTCGCGTTATCAGGTATTTACCGCTCAGCGCAAGCATTGGAACTAAACTTCGGGCACACCAAAGTTCCACCCAGTCCGCACCCAGTATGTCCGACCCTGCTTGTCTTTATATAGTTTCTGTG"
k = 5
n = len(dna)

dic = {}
for i in range(n-k+1):
  sub = dna[i:i+k]
  #print(sub)
  if sub not in dic.keys():
    dic[sub] = 1
  else:
    dic[sub] += 1

kmers = []
def create(s):
  if len(s) == k:
    kmers.append((s, 0))
    return
  create(s+'A')
  create(s+'C')
  create(s+'G')
  create(s+'T')

create('')
ans = []
for kmer in kmers:
  if kmer[0] in dic.keys():
    ans.append(dic[kmer[0]])
  else:
    ans.append(0)
for val in ans:
  print(val, end=" ")
